In [1]:
import pandas as pd


In [3]:
data=pd.read_csv('UniversalBank.csv')
data.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
data.isnull().sum()


ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [9]:
# Extraction of inde and dep
X=data.iloc[:, [1,2,3,4,5,6,7,8,10,11,12,13]].values # indep
Y=data.iloc[:, 9:10].values # dep


In [10]:
# splitting (70-30)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.3, random_state=10)

In [11]:
# Max Voting ----Way1 (DT, KNN, LR)
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [12]:
# Model Creation
model1=DecisionTreeClassifier()
model2=KNeighborsClassifier()
model3=LogisticRegression()
model1.fit(X_train, Y_train)
model2.fit(X_train, Y_train)
model3.fit(X_train, Y_train)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [13]:
# Prediction of all three model
pred1=model1.predict(X_test)
pred2=model2.predict(X_test)
pred3=model3.predict(X_test)


In [14]:
len(X_test)

1500

In [15]:
# Way1
import numpy as np
import statistics as s
final_pred=np.array([])
for i in range(0,len(X_test)):
 final_pred=np.append(final_pred, s.mode([pred1[i], pred2[i], pred3[i]]))

In [16]:
final_pred


array([0., 0., 0., ..., 0., 0., 0.])

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(final_pred, Y_test)
cm


array([[1334,   78],
       [  26,   62]], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(final_pred, Y_test)*100

93.06666666666666

In [22]:
# max voting with way 2 (inbuilt lib: VotingClassifeier)
from sklearn.ensemble import VotingClassifier


In [24]:
model1=DecisionTreeClassifier()
model2=KNeighborsClassifier()
model3=LogisticRegression()


In [25]:
max_vot_model=VotingClassifier(estimators=[('dt', model1), ('knn', model2), ('lr', model3)]
max_vot_model.fit(X_train, Y_train)


SyntaxError: invalid syntax (3350836270.py, line 2)

In [26]:
X_train

array([[58., 34., 80., ...,  0.,  1.,  1.],
       [41., 16., 30., ...,  0.,  0.,  1.],
       [33.,  7., 21., ...,  0.,  0.,  0.],
       ...,
       [49., 25., 93., ...,  0.,  1.,  0.],
       [50., 25., 45., ...,  0.,  0.,  0.],
       [46., 21., 82., ...,  0.,  0.,  0.]])

In [27]:
#AVERAGING
# model1=DecisionTreeClassifier()
model2=KNeighborsClassifier()
model3=LogisticRegression()
# model fitting
model1.fit(X_train, Y_train)
model2.fit(X_train, Y_train)
model3.fit(X_train, Y_train)
# Prediction of all three model
pred1=model1.predict(X_test)
pred2=model2.predict(X_test)
pred3=model3.predict(X_test)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [28]:
pred1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
# label encoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
pred1=le.fit_transform(pred1)
pred2=le.fit_transform(pred2)
pred3=le.fit_transform(pred3)

In [30]:
Y_test_new= le.fit_transform(Y_test)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [31]:
pred1, pred2, pred3

(array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 1, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [32]:
final_pred=(pred1+pred2+pred3)//3
final_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
Y_test_new

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [34]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(final_pred, Y_test_new)
cm

array([[1360,  118],
       [   0,   22]], dtype=int64)

In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(final_pred, Y_test_new)*100


92.13333333333334

In [36]:
#Weighted Average Approach
model1=DecisionTreeClassifier()
model2=KNeighborsClassifier()
model3=LogisticRegression()
# model fitting
model1.fit(X_train, Y_train)
model2.fit(X_train, Y_train)
model3.fit(X_train, Y_train)
# Prediction of all three model
pred1=model1.predict(X_test)
pred2=model2.predict(X_test)
pred3=model3.predict(X_test)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [37]:
w1=0.3 #(DT) 
w2=0.4 #(KNN)
w3=0.3 #(LR)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
pred1=le.fit_transform(pred1)
pred2=le.fit_transform(pred2)
pred3=le.fit_transform(pred3)
Y_test_new=le.fit_transform(Y_test) # actual Y
final_pred=w1*pred1+w2*pred2+w3*pred3
final_pred

C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0. , 0. , 0. , ..., 0.4, 0. , 0. ])

In [38]:
import numpy as np
final_pred=np.trunc(final_pred)
final_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [39]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(final_pred, Y_test_new)
cm

array([[1360,  118],
       [   0,   22]], dtype=int64)

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(final_pred, Y_test_new)*100


92.13333333333334

In [41]:
#STACKING APPROCH
from sklearn.ensemble import StackingClassifier
model1=DecisionTreeClassifier()
model2=KNeighborsClassifier()
model3=LogisticRegression()
# Stage 0
est=[('m1', model1), ('m2',model2)]
# stage1 model
stc=StackingClassifier(estimators=est,final_estimator=model3)

In [42]:
stc.fit(X_train, Y_train)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


StackingClassifier(estimators=[('m1', DecisionTreeClassifier()),
                               ('m2', KNeighborsClassifier())],
                   final_estimator=LogisticRegression())

In [43]:
Y_pred=stc.predict(X_test)


In [44]:
Y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [45]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(final_pred, Y_test_new)
cm


array([[1360,  118],
       [   0,   22]], dtype=int64)

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(final_pred, Y_test_new)*100

92.13333333333334

In [47]:
# Bagging classifier (Not going to execute)
# model 1 Bagging classifier with decision tree ---RF
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
# initialize the base classifier
base_clas=DecisionTreeClassifier()
clf=BaggingClassifier(base_estimator=base_clas, n_estimators=10, random_state=10)
clf.fit(X_train, Y_train)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(), random_state=10)

In [48]:
# Bagging classifier (Main)
# model 1 Bagging classifier with SVM ---RF
from sklearn.svm import SVC
# initialize the base classifier
base_clas=SVC()
clf=BaggingClassifier(base_estimator=base_clas, n_estimators=40, random_state=10)
clf.fit(X_train, Y_train)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=SVC(), n_estimators=40, random_state=10)

In [49]:
# predictions
Y_pred=clf.predict(X_test)


In [50]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test, Y_pred)
cm


array([[1360,    0],
       [ 140,    0]], dtype=int64)

In [51]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)*100


90.66666666666666

In [52]:
#boosting classifier
#AdaBoost
# base model --SVM
from sklearn.ensemble import AdaBoostClassifier
# initialize the base classifier
base_clas=SVC()
# model 1 Boosting classifier with SVM ---RF
from sklearn.svm import SVC
adbc=AdaBoostClassifier(base_estimator=base_clas, n_estimators=100,algorithm='SAMME')
adbc.fit(X_train, Y_train)

C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(algorithm='SAMME', base_estimator=SVC(), n_estimators=100)

In [53]:
# base mode -- LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
# initialize the base classifier
base_clas=LogisticRegression()
adbc=AdaBoostClassifier(base_estimator=base_clas, n_estimators=100)
adbc.fit(X_train, Y_train)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(base_estimator=LogisticRegression(), n_estimators=100)

In [54]:
# base mode -- Decision tree
from sklearn.tree import DecisionTreeClassifier
# initialize the base classifier
base_clas=DecisionTreeClassifier()
adbc=AdaBoostClassifier(base_estimator=base_clas, n_estimators=100, random_state=1)
adbc.fit(X_train, Y_train)

C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=100,
                   random_state=1)

In [55]:
# predictions
Y_pred=adbc.predict(X_test)


In [56]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test, Y_pred)
cm

array([[1351,    9],
       [  14,  126]], dtype=int64)

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)*100

98.46666666666667