In [73]:
import pandas as pd


In [74]:
data=pd.read_csv('UniversalBank.csv')
data.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [75]:
data.isnull().sum()


ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [76]:
# Extraction of inde and dep
X=data.iloc[:, [1,2,3,4,5,6,7,8,10,11,12,13]].values # indep
Y=data.iloc[:, 9:10].values # dep


In [77]:
# splitting (70-30)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.3, random_state=10)

In [78]:
# Max Voting ----Way2 (DT, KNN, LR, RF, SVC)
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [79]:
# Model Creation
model1 = DecisionTreeClassifier()
model2 = KNeighborsClassifier()
model3 = LogisticRegression()
model4 = RandomForestClassifier()
model5 = GaussianNB()
model6 = SVC()

model1.fit(X_train, Y_train)
model2.fit(X_train, Y_train)
model3.fit(X_train, Y_train)
model4.fit(X_train, Y_train)
model5.fit(X_train, Y_train)
model6.fit(X_train, Y_train)



C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\shaurya khanna\AppData\Local\Temp\ipykernel_26336\2768723465.py:12: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model4.fit(X_train, Y_train)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the sh

SVC()

In [86]:
# Prediction of  6 model
pred1 = model1.predict(X_test)
pred2 = model2.predict(X_test)
pred3 = model3.predict(X_test)
pred4 = model4.predict(X_test)
pred5 = model5.predict(X_test)
pred6 = model6.predict(X_test)


In [87]:
len(X_test)

1500

In [88]:
# Way1
import numpy as np
import statistics as s
final_pred=np.array([])
for i in range(0,len(X_test)):
 final_pred=np.append(final_pred, s.mode([pred1[i], pred2[i], pred3[i],pred4[i],pred5[i],pred6[i]]))

In [89]:
final_pred


array([0., 0., 0., ..., 0., 0., 0.])

In [90]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(final_pred, Y_test)
cm


array([[1360,   44],
       [   0,   96]], dtype=int64)

In [91]:
from sklearn.metrics import accuracy_score
accuracy_score(final_pred, Y_test)*100

97.06666666666666

In [92]:
# max voting with way 2 (inbuilt lib: VotingClassifeier)
from sklearn.ensemble import VotingClassifier


In [93]:
model1 = DecisionTreeClassifier()
model2 = KNeighborsClassifier()
model3 = LogisticRegression()
model4 = RandomForestClassifier()
model5 = GaussianNB()
model6 = SVC()


In [94]:
max_vot_model=VotingClassifier(estimators=[('dt', model1), ('knn', model2), ('lr', model3),('rfc',model4),('gnb',model5),('svc',model6)]
max_vot_model.fit(X_train, Y_train)


SyntaxError: invalid syntax (4192018173.py, line 2)

In [95]:
X_train

array([[58., 34., 80., ...,  0.,  1.,  1.],
       [41., 16., 30., ...,  0.,  0.,  1.],
       [33.,  7., 21., ...,  0.,  0.,  0.],
       ...,
       [49., 25., 93., ...,  0.,  1.,  0.],
       [50., 25., 45., ...,  0.,  0.,  0.],
       [46., 21., 82., ...,  0.,  0.,  0.]])

In [96]:
#AVERAGING
model1=DecisionTreeClassifier()
model2=KNeighborsClassifier()
model3=LogisticRegression()
model4 = RandomForestClassifier()
model5 = GaussianNB()
model6 = SVC()

# model fitting
model1.fit(X_train, Y_train)
model2.fit(X_train, Y_train)
model3.fit(X_train, Y_train)
model4.fit(X_train, Y_train)
model5.fit(X_train, Y_train)
model6.fit(X_train, Y_train)

# Prediction of all three model
pred1=model1.predict(X_test)
pred2=model2.predict(X_test)
pred3=model3.predict(X_test)
pred4 = model4.predict(X_test)
pred5 = model5.predict(X_test)
pred6 = model6.predict(X_test)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\shaurya khanna\AppData\Local\Temp\ipykernel_26336\1721133397.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model4.fit(X_train, Y_train)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the sh

In [97]:
pred1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [98]:
# label encoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
pred1=le.fit_transform(pred1)
pred2=le.fit_transform(pred2)
pred3=le.fit_transform(pred3)
pred4=le.fit_transform(pred4)
pred5=le.fit_transform(pred5)
pred6=le.fit_transform(pred6)

In [99]:
Y_test_new= le.fit_transform(Y_test)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [100]:
pred1, pred2, pred3,pred4,pred5,pred6

(array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 1, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [101]:
final_pred=(pred1+pred2+pred3+pred4+pred5+pred6)//6
final_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [102]:
Y_test_new

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [103]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(final_pred, Y_test_new)
cm

array([[1360,  140],
       [   0,    0]], dtype=int64)

In [104]:
from sklearn.metrics import accuracy_score
accuracy_score(final_pred, Y_test_new)*100


90.66666666666666

In [105]:
#Weighted Average Approach
model1=DecisionTreeClassifier()
model2=KNeighborsClassifier()
model3=LogisticRegression()
model4 = RandomForestClassifier()
model5 = GaussianNB()
model6 = SVC()

# model fitting
model1.fit(X_train, Y_train)
model2.fit(X_train, Y_train)
model3.fit(X_train, Y_train)
model4.fit(X_train, Y_train)
model5.fit(X_train, Y_train)
model6.fit(X_train, Y_train)

# Prediction of all three model
pred1=model1.predict(X_test)
pred2=model2.predict(X_test)
pred3=model3.predict(X_test)
pred4 = model4.predict(X_test)
pred5 = model5.predict(X_test)
pred6 = model6.predict(X_test)

C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\shaurya khanna\AppData\Local\Temp\ipykernel_26336\640826486.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model4.fit(X_train, Y_train)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the sha

In [106]:
w1=0.10 #(DT) 
w2=0.10 #(KNN)
w3=0.20 #(LR)
w4=0.10
w5=0.20
w6=0.10
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
pred1=le.fit_transform(pred1)
pred2=le.fit_transform(pred2)
pred3=le.fit_transform(pred3)
pred4=le.fit_transform(pred4)
pred5=le.fit_transform(pred5)
pred6=le.fit_transform(pred6)

Y_test_new=le.fit_transform(Y_test) # actual Y
final_pred=w1*pred1+w2*pred2+w3*pred3+w4*pred4+w5*pred5+w6*pred6
final_pred

C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0. , 0. , 0. , ..., 0.1, 0. , 0. ])

In [107]:
import numpy as np
final_pred=np.trunc(final_pred)
final_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [108]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(final_pred, Y_test_new)
cm

array([[1360,  140],
       [   0,    0]], dtype=int64)

In [109]:
from sklearn.metrics import accuracy_score
accuracy_score(final_pred, Y_test_new)*100


90.66666666666666

In [116]:
#STACKING APPROCH
from sklearn.ensemble import StackingClassifier
model1=DecisionTreeClassifier()
model2=KNeighborsClassifier()
model3=LogisticRegression()
model4 = RandomForestClassifier()
model5 = GaussianNB()
model6 = SVC()
# Stage 0
est=[('m1', model1), ('m2',model2),('m4',model4),('m5',model5),('m6',model6)]
# stage1 model
stc=StackingClassifier(estimators=est,final_estimator=model3)

In [117]:
stc.fit(X_train, Y_train)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


StackingClassifier(estimators=[('m1', DecisionTreeClassifier()),
                               ('m2', KNeighborsClassifier()),
                               ('m4', RandomForestClassifier()),
                               ('m5', GaussianNB()), ('m6', SVC())],
                   final_estimator=LogisticRegression())

In [118]:
Y_pred=stc.predict(X_test)


In [119]:
Y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [120]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(final_pred, Y_test_new)
cm


array([[1360,  140],
       [   0,    0]], dtype=int64)

In [121]:
from sklearn.metrics import accuracy_score
accuracy_score(final_pred, Y_test_new)*100

90.66666666666666

In [64]:
# Bagging classifier (Not going to execute)
# model 1 Bagging classifier with decision tree ---RF
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
# initialize the base classifier
base_clas=DecisionTreeClassifier()
clf=BaggingClassifier(base_estimator=base_clas, n_estimators=10, random_state=10)
clf.fit(X_train, Y_train)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(), random_state=10)

In [65]:
# Bagging classifier (Main)
# model 1 Bagging classifier with SVM ---RF
from sklearn.svm import SVC
# initialize the base classifier
base_clas=SVC()
clf=BaggingClassifier(base_estimator=base_clas, n_estimators=40, random_state=10)
clf.fit(X_train, Y_train)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=SVC(), n_estimators=40, random_state=10)

In [66]:
# predictions
Y_pred=clf.predict(X_test)


In [67]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test, Y_pred)
cm


array([[1360,    0],
       [ 140,    0]], dtype=int64)

In [68]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)*100


90.66666666666666

In [69]:
#boosting classifier
#AdaBoost
# base model --SVM
from sklearn.ensemble import AdaBoostClassifier
# initialize the base classifier
base_clas=SVC()
# model 1 Boosting classifier with SVM ---RF
from sklearn.svm import SVC
adbc=AdaBoostClassifier(base_estimator=base_clas, n_estimators=100,algorithm='SAMME')
adbc.fit(X_train, Y_train)

C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(algorithm='SAMME', base_estimator=SVC(), n_estimators=100)

In [70]:
# base mode -- LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
# initialize the base classifier
base_clas=LogisticRegression()
adbc=AdaBoostClassifier(base_estimator=base_clas, n_estimators=100)
adbc.fit(X_train, Y_train)


C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(base_estimator=LogisticRegression(), n_estimators=100)

In [54]:
# base mode -- Decision tree
from sklearn.tree import DecisionTreeClassifier
# initialize the base classifier
base_clas=DecisionTreeClassifier()
adbc=AdaBoostClassifier(base_estimator=base_clas, n_estimators=100, random_state=1)
adbc.fit(X_train, Y_train)

C:\Users\shaurya khanna\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=100,
                   random_state=1)

In [55]:
# predictions
Y_pred=adbc.predict(X_test)


In [71]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test, Y_pred)
cm

array([[1360,    0],
       [ 140,    0]], dtype=int64)

In [72]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)*100

90.66666666666666